--Military
NDefines.NMilitary.ENCIRCLED_DISBAND_MANPOWER_FACTOR = 0
NDefines.NMilitary.PLAYER_ORDER_PLANNING_DECAY = 0.03
NDefines.NMilitary.BASE_DIVISION_BRIGADE_GROUP_COST = 1
NDefines.NMilitary.BASE_DIVISION_BRIGADE_CHANGE_COST = 3
NDefines.NMilitary.BASE_DIVISION_SUPPORT_SLOT_COST = 5
NDefines.NMilitary.TRAINING_ATTRITION = 0.03
